### ISSUE TITLE
Improvement in typescript and web3

### ISSUE THREAD

**Issue by ondratra** [krzkaczor/TypeChain#67]
I propose changes to generated code:
- `export default` instead of plain `export` in generated classes
- replace `web3.eth.contract(contractAbi).at(address)` with `new web3.eth.Contract(contractAbi, address)` in generated classes
-> support for [web3 1.x](https://github.com/trufflesuite/ganache-cli/issues/382#issuecomment-346136763) 
- create new exposed function `abi2wrapper(abi: Object, options: Object): string` that convert single ABI to TS wrapper class and will contain most of `processFile()`'s source code (calling `generateSource`)

**Comment by krzkaczor** [comment]
Hey!
Sorry to keep you waiting, I somehow missed this issue.

I think all of these problems will be solved when typechain starts to support user-provided templates but here's my reasoning:

1. https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad
2. Support for 1.x is discussed in: https://github.com/krzkaczor/TypeChain/issues/25
3. The problem here is how to link generated files with the runtime. I think runtime path has to be part of options object here.

**Comment by krzkaczor** [comment]
3 is covered by https://github.com/krzkaczor/TypeChain/pull/72 Thanks! Others are already discussed so I am gonna close this for now.
